Welcome = "Benvenuto nel Boardgame Night Bot! 🎲\nSiamo qui per aiutarti a organizzare la tua serata di giochi da tavolo.\nUtilizzo:\nUsa /create [nome evento] per creare un nuovo evento, aggiungi il 🔒 se vuoi che l'evento sia modificabile solo da te.\nUsa /add_game [nome gioco] per aggiungere giochi all'evento.\nUsa /language [lan] per impostare la lingua del bot.\nClicca sui pulsanti per unirti o lasciare un gioco.\nDivertiti! 🎉"  

Usage = "Utilizzo: {{.Command}} {{.Example}}"

EventName = "nome evento"
GameName = "nome gioco"

FailedToCreateEvent = "Impossibile creare l'evento. Per favore riprova."  
FailedToAddGame = "Impossibile aggiungere il gioco. Per favore riprova."  
FailedToUpdateMessageEvent = "Impossibile aggiornare il messaggio. Per favore riprova."  
FailedToUpdateGame = "Impossibile aggiornare il gioco. Per favore riprova."  
FailedToGetGameInfo = "Impossibile ottenere le informazioni del gioco da BoardGameGeek. Per favore riprova."  
FailedToSetLanguage = "Impostazione della lingua non riuscita. Per favore riprova."
FailedToAddPlayer = "Impossibile aggiungere il giocatore. Per favore riprova."  
FailedToRemovePlayer = "Impossibile rimuovere il giocatore. Per favore riprova." 
FailedLanguageNotAvailable = "Lingua non disponibile. Per favore riprova con una di queste lingue disponibili: {{.AvailableLanguages}}."

InvalidNumberOfPlayers = "Numero di giocatori non valido. Per favore riprova."  
InvalidBggURL = "L'URL di BoardGameGeek è invalido. Per favore riprova."
InvalidData = "Dati non validi. Per favore riprova."

GameAdded = "Gioco <b>{{.Name}}</b>{{.Link}} aggiunto! (1/{{.MaxPlayers}} giocatori).\nRispondi a questo messaggio con il numero massimo di giocatori per aggiornarlo (predefinito {{.MaxPlayers}}).\nPuoi anche inviarmi il link di https://boardgamegeek.com/ per aggiornare le informazioni del gioco.\nClicca sul pulsante per partecipare."
GameUpdated = "Gioco aggiornato!"
LanguageSet = "Lingua impostata su {{.Language}}."

GameNotFound = "Gioco non trovato. Stai cercando di aggiornare le informazioni di un gioco che non esiste. Probabilmente stai commentando il messaggio sbagliato."  
EventNotFound = "Evento non trovato."
EventLocked = "L'evento è bloccato 🔒. Solo il creatore può aggiornare l'evento o aggiungere giochi."

Join = "Partecipa a {{.Name}}"
JoinEvent = "Partecipa all'evento"  
UpdatedAt = "<i>Aggiornato alle {{.Time}}</i>"  
Update = "Aggiorna"
NotComing = "Non partecipo"
AddGame = "Aggiungi un gioco"
Players = "partecipanti"

Open = "Premi qui per aprire le impostazioni dell'evento {{.Name}} e partecipare."


WebNoParticipants = "Ancora nessun partecipante."
WebPlayers = "partecipanti"
WebJoin = "Unisciti"
WebAddGame = "Aggiungi un gioco"
WebAddNewGame = "Aggiungi un nuovo gioco"
WebWelcome = "Benvenuto/a"
WebGameName = "Nome del gioco"
WebMaxPlayers = "Giocatori massimi"
WebUpdatedAt = "Aggiornato al {{.Time}}"
WebUpdateGame = "Aggiorna il gioco"
WebUnlinkFormBoardGameGeek = "Scollega da BoardGameGeek"
WebSomethingWentWrong = "Qualcosa è andato storto"