Welcome = "Benvenuto nel Boardgame Night Bot! 🎲\nSiamo qui per aiutarti a organizzare la tua serata di giochi da tavolo.\nUtilizzo:\nUsa /create [nome evento] per creare un nuovo evento.\nUsa /add_game [nome gioco] per aggiungere giochi all'evento.\nUsa /language [lan] per impostare la lingua del bot.\nClicca sui pulsanti per unirti o lasciare un gioco.\nDivertiti! 🎉"  

Usage = "Utilizzo: {{.Command}} {{.Example}}"

EventName = "nome evento"
GameName = "nome gioco"

FailedToCreateEvent = "Impossibile creare l'evento. Per favore riprova."  
FailedToAddGame = "Impossibile aggiungere il gioco. Per favore riprova."  
FailedToUpdateMessageEvent = "Impossibile aggiornare il messaggio. Per favore riprova."  
FailedToUpdateGame = "Impossibile aggiornare il gioco. Per favore riprova."  
FailedToGetGameInfo = "Impossibile ottenere le informazioni del gioco da BoardGameGeek. Per favore riprova."  
FailedToSetLanguage = "Impostazione della lingua non riuscita. Per favore riprova."
FailedToAddPlayer = "Impossibile aggiungere il giocatore. Per favore riprova."  
FailedToRemovePlayer = "Impossibile rimuovere il giocatore. Per favore riprova."  

InvalidNumberOfPlayers = "Numero di giocatori non valido. Per favore riprova."  
InvalidBggURL = "L'URL di BoardGameGeek è invalido. Per favore riprova."

EventCreated = "📆 <b>{{.Name}}</b>\nNessun gioco aggiunto ancora, usa /add_game per aggiungere giochi."  
GameAdded = "Gioco <b>{{.Name}}</b>{{.Link}} aggiunto! (1/{{.MaxPlayers}} giocatori).\nRispondi a questo messaggio con il numero massimo di giocatori per aggiornarlo (predefinito {{.MaxPlayers}}).\nPuoi anche inviarmi il link di https://boardgamegeek.com/ per aggiornare le informazioni del gioco.\nClicca sul pulsante per partecipare."
GameUpdated = "Gioco aggiornato!"

GameNotFound = "Gioco non trovato. Stai cercando di aggiornare le informazioni di un gioco che non esiste. Probabilmente stai commentando il messaggio sbagliato."  
EventNotFound = "Evento non trovato."

Join = "Partecipa a {{.Name}}"  
UpdatedAt = "<i>Aggiornato alle {{.Time}}</i>\nUsa /add_game per aggiungere altri giochi"  
